---
- name: Carregar variáveis globais
  hosts: all
  gather_facts: no
  tasks:
    - name: Incluir variáveis do grupo all
      include_vars:
        file: inventory/group_vars/all.yml

- name: Testar carregamento das variáveis
  hosts: all
  gather_facts: no
  tasks:
    - name: Exibir variáveis do grupo all
      debug:
        var: hostvars[inventory_hostname]

- name: Pre-flight checks
  hosts: all
  become: yes
  gather_facts: yes
  tags: [always, diagnose]
  tasks:
    - name: Include diagnóstico
      include_tasks: tasks/diagnostico.yml

- name: Instalar e configurar OCS Inventory Agent
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - ocs_inventory

- name: Verificar instalação
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Verificar status do agente OCS
      shell: "ps aux | grep -v grep | grep ocsinventory-agent"
      register: ocs_status
      failed_when: false
      changed_when: false

    - name: Exibir status da instalação
      debug:
        msg: "OCS Inventory Agent instalado com sucesso em {{ inventory_hostname }}"
      when: ocs_status.rc == 0

    - name: Registrar hosts com falha
      set_fact:
        installation_failed: true
      when: ocs_status.rc != 0
      delegate_to: localhost
      delegate_facts: true

- hosts: all
  become: yes
  vars:
    backup_dir: "/var/backups/ocsinventory"
  roles:
    - ocs_inventory
